# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
locale                   : "en"
title                    : "Dev Meets Ops"
title_separator          : "|"
name                     : "Brian Marsh"
description              : ""
url                      : "https://devmeetsops.com/"
enforce_ssl              : "devmeetsops.com"
baseurl                  : # the subpath of your site, e.g. "/blog"
repository               : "pezhore/pezhore.github.io"
teaser                   : # filename of teaser fallback teaser image placed in /images/, .e.g. "500x300.png"
breadcrumbs              : true # true, false (default)
permalink                : /:categories/:title/
words_per_minute         : 200
baseurl                  : "" # the subpath of your site, e.g. /blog
github: [metadata]

defaults:
    - scope:
        path: ""
        type: posts
      values:
        author_profile: true
        classes: wide
# Author Settings
author:
  name             : "Brian Marsh"
  avatar           : "/images/bio-photo.jpg"
  bio              : ""
  location         : "Middle America"
  email            :
  uri              :
  bitbucket        :
  codepen          :
  dribbble         :
  flickr           :
  facebook         :
  foursquare       :
  github           : "pezhore"
  google_plus      :
  keybase          :
  instagram        :
  lastfm           :
  linkedin         : "briankmarsh"
  pinterest        :
  soundcloud       :
  stackoverflow    : # "123456/username" (the last part of your profile url, e.g. http://stackoverflow.com/users/123456/username)
  steam            :
  tumblr           :
  twitter          : "pezhore"
  vine             :
  weibo            :
  xing             :
  youtube          :

# Build settings
markdown: kramdown
#theme: minima
remote_theme: "mmistakes/minimal-mistakes@4.13.0"
plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-sitemap
  - jemoji
  - jekyll-include-cache

paginate: 5
paginate_path: /page:num/
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
include: ["_pages"]
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

